akka {
  actor {
    default-dispatcher {
      type = Dispatcher
      executor = fork-join-executor
      throughput = 100
    }

    book-dispatcher {
      type = Dispatcher
      executor = fork-join-executor
      throughput = 50
    }
  }
}